/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoOutsourcingRouteImport } from './routes/seo-outsourcing'
import { Route as FreeSeoAuditRouteImport } from './routes/free-seo-audit'
import { Route as FiverrSeoProblemsRouteImport } from './routes/fiverr-seo-problems'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWordpressSeoRouteImport } from './routes/services.wordpress-seo'
import { Route as ServicesTechnicalSeoRouteImport } from './routes/services.technical-seo'
import { Route as ServicesShopifySeoRouteImport } from './routes/services.shopify-seo'
import { Route as ServicesLocalSeoRouteImport } from './routes/services.local-seo'
import { Route as ServicesLinkBuildingRouteImport } from './routes/services.link-building'
import { Route as ServicesEcommerceSeoRouteImport } from './routes/services.ecommerce-seo'
import { Route as ServicesContentSeoRouteImport } from './routes/services.content-seo'
import { Route as ServicesAiSeoRouteImport } from './routes/services.ai-seo'
import { Route as CountriesUsaSeoRouteImport } from './routes/countries.usa-seo'
import { Route as CountriesUkSeoRouteImport } from './routes/countries.uk-seo'
import { Route as CountriesCanadaSeoRouteImport } from './routes/countries.canada-seo'
import { Route as CountriesAustraliaSeoRouteImport } from './routes/countries.australia-seo'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOutsourcingRoute = SeoOutsourcingRouteImport.update({
  id: '/seo-outsourcing',
  path: '/seo-outsourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeSeoAuditRoute = FreeSeoAuditRouteImport.update({
  id: '/free-seo-audit',
  path: '/free-seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FiverrSeoProblemsRoute = FiverrSeoProblemsRouteImport.update({
  id: '/fiverr-seo-problems',
  path: '/fiverr-seo-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWordpressSeoRoute = ServicesWordpressSeoRouteImport.update({
  id: '/wordpress-seo',
  path: '/wordpress-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTechnicalSeoRoute = ServicesTechnicalSeoRouteImport.update({
  id: '/technical-seo',
  path: '/technical-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesShopifySeoRoute = ServicesShopifySeoRouteImport.update({
  id: '/shopify-seo',
  path: '/shopify-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLocalSeoRoute = ServicesLocalSeoRouteImport.update({
  id: '/local-seo',
  path: '/local-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLinkBuildingRoute = ServicesLinkBuildingRouteImport.update({
  id: '/link-building',
  path: '/link-building',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEcommerceSeoRoute = ServicesEcommerceSeoRouteImport.update({
  id: '/ecommerce-seo',
  path: '/ecommerce-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesContentSeoRoute = ServicesContentSeoRouteImport.update({
  id: '/content-seo',
  path: '/content-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiSeoRoute = ServicesAiSeoRouteImport.update({
  id: '/ai-seo',
  path: '/ai-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const CountriesUsaSeoRoute = CountriesUsaSeoRouteImport.update({
  id: '/countries/usa-seo',
  path: '/countries/usa-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesUkSeoRoute = CountriesUkSeoRouteImport.update({
  id: '/countries/uk-seo',
  path: '/countries/uk-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCanadaSeoRoute = CountriesCanadaSeoRouteImport.update({
  id: '/countries/canada-seo',
  path: '/countries/canada-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesAustraliaSeoRoute = CountriesAustraliaSeoRouteImport.update({
  id: '/countries/australia-seo',
  path: '/countries/australia-seo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/fiverr-seo-problems': typeof FiverrSeoProblemsRoute
  '/free-seo-audit': typeof FreeSeoAuditRoute
  '/seo-outsourcing': typeof SeoOutsourcingRoute
  '/services': typeof ServicesRouteWithChildren
  '/countries/australia-seo': typeof CountriesAustraliaSeoRoute
  '/countries/canada-seo': typeof CountriesCanadaSeoRoute
  '/countries/uk-seo': typeof CountriesUkSeoRoute
  '/countries/usa-seo': typeof CountriesUsaSeoRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-seo': typeof ServicesContentSeoRoute
  '/services/ecommerce-seo': typeof ServicesEcommerceSeoRoute
  '/services/link-building': typeof ServicesLinkBuildingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/shopify-seo': typeof ServicesShopifySeoRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/services/wordpress-seo': typeof ServicesWordpressSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/fiverr-seo-problems': typeof FiverrSeoProblemsRoute
  '/free-seo-audit': typeof FreeSeoAuditRoute
  '/seo-outsourcing': typeof SeoOutsourcingRoute
  '/services': typeof ServicesRouteWithChildren
  '/countries/australia-seo': typeof CountriesAustraliaSeoRoute
  '/countries/canada-seo': typeof CountriesCanadaSeoRoute
  '/countries/uk-seo': typeof CountriesUkSeoRoute
  '/countries/usa-seo': typeof CountriesUsaSeoRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-seo': typeof ServicesContentSeoRoute
  '/services/ecommerce-seo': typeof ServicesEcommerceSeoRoute
  '/services/link-building': typeof ServicesLinkBuildingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/shopify-seo': typeof ServicesShopifySeoRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/services/wordpress-seo': typeof ServicesWordpressSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/fiverr-seo-problems': typeof FiverrSeoProblemsRoute
  '/free-seo-audit': typeof FreeSeoAuditRoute
  '/seo-outsourcing': typeof SeoOutsourcingRoute
  '/services': typeof ServicesRouteWithChildren
  '/countries/australia-seo': typeof CountriesAustraliaSeoRoute
  '/countries/canada-seo': typeof CountriesCanadaSeoRoute
  '/countries/uk-seo': typeof CountriesUkSeoRoute
  '/countries/usa-seo': typeof CountriesUsaSeoRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-seo': typeof ServicesContentSeoRoute
  '/services/ecommerce-seo': typeof ServicesEcommerceSeoRoute
  '/services/link-building': typeof ServicesLinkBuildingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/shopify-seo': typeof ServicesShopifySeoRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/services/wordpress-seo': typeof ServicesWordpressSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/fiverr-seo-problems'
    | '/free-seo-audit'
    | '/seo-outsourcing'
    | '/services'
    | '/countries/australia-seo'
    | '/countries/canada-seo'
    | '/countries/uk-seo'
    | '/countries/usa-seo'
    | '/services/ai-seo'
    | '/services/content-seo'
    | '/services/ecommerce-seo'
    | '/services/link-building'
    | '/services/local-seo'
    | '/services/shopify-seo'
    | '/services/technical-seo'
    | '/services/wordpress-seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/fiverr-seo-problems'
    | '/free-seo-audit'
    | '/seo-outsourcing'
    | '/services'
    | '/countries/australia-seo'
    | '/countries/canada-seo'
    | '/countries/uk-seo'
    | '/countries/usa-seo'
    | '/services/ai-seo'
    | '/services/content-seo'
    | '/services/ecommerce-seo'
    | '/services/link-building'
    | '/services/local-seo'
    | '/services/shopify-seo'
    | '/services/technical-seo'
    | '/services/wordpress-seo'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/fiverr-seo-problems'
    | '/free-seo-audit'
    | '/seo-outsourcing'
    | '/services'
    | '/countries/australia-seo'
    | '/countries/canada-seo'
    | '/countries/uk-seo'
    | '/countries/usa-seo'
    | '/services/ai-seo'
    | '/services/content-seo'
    | '/services/ecommerce-seo'
    | '/services/link-building'
    | '/services/local-seo'
    | '/services/shopify-seo'
    | '/services/technical-seo'
    | '/services/wordpress-seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  FiverrSeoProblemsRoute: typeof FiverrSeoProblemsRoute
  FreeSeoAuditRoute: typeof FreeSeoAuditRoute
  SeoOutsourcingRoute: typeof SeoOutsourcingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  CountriesAustraliaSeoRoute: typeof CountriesAustraliaSeoRoute
  CountriesCanadaSeoRoute: typeof CountriesCanadaSeoRoute
  CountriesUkSeoRoute: typeof CountriesUkSeoRoute
  CountriesUsaSeoRoute: typeof CountriesUsaSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-outsourcing': {
      id: '/seo-outsourcing'
      path: '/seo-outsourcing'
      fullPath: '/seo-outsourcing'
      preLoaderRoute: typeof SeoOutsourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-seo-audit': {
      id: '/free-seo-audit'
      path: '/free-seo-audit'
      fullPath: '/free-seo-audit'
      preLoaderRoute: typeof FreeSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiverr-seo-problems': {
      id: '/fiverr-seo-problems'
      path: '/fiverr-seo-problems'
      fullPath: '/fiverr-seo-problems'
      preLoaderRoute: typeof FiverrSeoProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wordpress-seo': {
      id: '/services/wordpress-seo'
      path: '/wordpress-seo'
      fullPath: '/services/wordpress-seo'
      preLoaderRoute: typeof ServicesWordpressSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technical-seo': {
      id: '/services/technical-seo'
      path: '/technical-seo'
      fullPath: '/services/technical-seo'
      preLoaderRoute: typeof ServicesTechnicalSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/shopify-seo': {
      id: '/services/shopify-seo'
      path: '/shopify-seo'
      fullPath: '/services/shopify-seo'
      preLoaderRoute: typeof ServicesShopifySeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/local-seo': {
      id: '/services/local-seo'
      path: '/local-seo'
      fullPath: '/services/local-seo'
      preLoaderRoute: typeof ServicesLocalSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/link-building': {
      id: '/services/link-building'
      path: '/link-building'
      fullPath: '/services/link-building'
      preLoaderRoute: typeof ServicesLinkBuildingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ecommerce-seo': {
      id: '/services/ecommerce-seo'
      path: '/ecommerce-seo'
      fullPath: '/services/ecommerce-seo'
      preLoaderRoute: typeof ServicesEcommerceSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content-seo': {
      id: '/services/content-seo'
      path: '/content-seo'
      fullPath: '/services/content-seo'
      preLoaderRoute: typeof ServicesContentSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-seo': {
      id: '/services/ai-seo'
      path: '/ai-seo'
      fullPath: '/services/ai-seo'
      preLoaderRoute: typeof ServicesAiSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/countries/usa-seo': {
      id: '/countries/usa-seo'
      path: '/countries/usa-seo'
      fullPath: '/countries/usa-seo'
      preLoaderRoute: typeof CountriesUsaSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/uk-seo': {
      id: '/countries/uk-seo'
      path: '/countries/uk-seo'
      fullPath: '/countries/uk-seo'
      preLoaderRoute: typeof CountriesUkSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/canada-seo': {
      id: '/countries/canada-seo'
      path: '/countries/canada-seo'
      fullPath: '/countries/canada-seo'
      preLoaderRoute: typeof CountriesCanadaSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/australia-seo': {
      id: '/countries/australia-seo'
      path: '/countries/australia-seo'
      fullPath: '/countries/australia-seo'
      preLoaderRoute: typeof CountriesAustraliaSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiSeoRoute: typeof ServicesAiSeoRoute
  ServicesContentSeoRoute: typeof ServicesContentSeoRoute
  ServicesEcommerceSeoRoute: typeof ServicesEcommerceSeoRoute
  ServicesLinkBuildingRoute: typeof ServicesLinkBuildingRoute
  ServicesLocalSeoRoute: typeof ServicesLocalSeoRoute
  ServicesShopifySeoRoute: typeof ServicesShopifySeoRoute
  ServicesTechnicalSeoRoute: typeof ServicesTechnicalSeoRoute
  ServicesWordpressSeoRoute: typeof ServicesWordpressSeoRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiSeoRoute: ServicesAiSeoRoute,
  ServicesContentSeoRoute: ServicesContentSeoRoute,
  ServicesEcommerceSeoRoute: ServicesEcommerceSeoRoute,
  ServicesLinkBuildingRoute: ServicesLinkBuildingRoute,
  ServicesLocalSeoRoute: ServicesLocalSeoRoute,
  ServicesShopifySeoRoute: ServicesShopifySeoRoute,
  ServicesTechnicalSeoRoute: ServicesTechnicalSeoRoute,
  ServicesWordpressSeoRoute: ServicesWordpressSeoRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  FiverrSeoProblemsRoute: FiverrSeoProblemsRoute,
  FreeSeoAuditRoute: FreeSeoAuditRoute,
  SeoOutsourcingRoute: SeoOutsourcingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  CountriesAustraliaSeoRoute: CountriesAustraliaSeoRoute,
  CountriesCanadaSeoRoute: CountriesCanadaSeoRoute,
  CountriesUkSeoRoute: CountriesUkSeoRoute,
  CountriesUsaSeoRoute: CountriesUsaSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
